server:
  port: 5100
spring:
  application:
    name: dijkstra
eureka:
  client:
    service-url.defaultZone: http://localhost:3100/eureka/
zuul:
  routes:
    turing:
      path: /feign/**
      serviceId: turing

